run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errchkjson
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - misspell
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - typecheck
    - unconvert
    - unused
