name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17, 1.18]

    services:
      postgres:
        image: postgres:13.0
        env:
          POSTGRES_USER: dcrpooluser
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: dcrpooltestdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2"
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          ./run_tests.sh
