name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21', '1.22']

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: dcrpooluser
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: dcrpooltestdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #v5.0.1
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.0"
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          ./run_tests.sh
